-- Dev-only seed data for learning-service (Flyway V2, loaded only by the dev profile).
-- GENERATED by tools/gen_seed.py - edit that script and regenerate, do not hand-edit.

INSERT INTO term (id, name, start_date, end_date, is_current, max_credits, quarter, academic_year)
VALUES ('q1-2026', 'Q1 · Fall 2026', '2026-08-24', '2026-10-23', true, 30, 1, '2026-2027');

-- AP Pre Calculus: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-precalc', 'AP Pre Calculus', 'Junior', 'Dr John Anderson', 'blue', 52, 'in-progress', 'janderson');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-precalc', 'q1-2026', 1, '2026-08-24', 'Unit 1: Functions and Graphs', 'Functions and Graphs — lesson 1', true, '2026-08-24 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 2, '2026-08-26', 'Unit 1: Functions and Graphs', 'Functions and Graphs — lesson 2', true, '2026-08-26 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 3, '2026-08-28', 'Unit 1: Functions and Graphs', 'Functions and Graphs — lesson 3 (unit review)', true, '2026-08-28 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 4, '2026-08-31', 'Unit 2: Polynomial Functions', 'Polynomial Functions — lesson 1', true, '2026-08-31 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 5, '2026-09-02', 'Unit 2: Polynomial Functions', 'Polynomial Functions — lesson 2', true, '2026-09-02 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 6, '2026-09-04', 'Unit 2: Polynomial Functions', 'Polynomial Functions — lesson 3 (unit review)', true, '2026-09-04 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 7, '2026-09-07', 'Unit 3: Rational Functions', 'Rational Functions — lesson 1', true, '2026-09-07 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 8, '2026-09-09', 'Unit 3: Rational Functions', 'Rational Functions — lesson 2', true, '2026-09-09 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 9, '2026-09-11', 'Unit 3: Rational Functions', 'Rational Functions — lesson 3 (unit review)', true, '2026-09-11 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 10, '2026-09-14', 'Unit 4: Exponential Functions', 'Exponential Functions — lesson 1', true, '2026-09-14 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 11, '2026-09-16', 'Unit 4: Exponential Functions', 'Exponential Functions — lesson 2', true, '2026-09-16 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 12, '2026-09-18', 'Unit 4: Exponential Functions', 'Exponential Functions — lesson 3 (unit review)', true, '2026-09-18 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 13, '2026-09-21', 'Unit 5: Logarithmic Functions', 'Logarithmic Functions — lesson 1', true, '2026-09-21 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 14, '2026-09-23', 'Unit 5: Logarithmic Functions', 'Logarithmic Functions — lesson 2', true, '2026-09-23 16:00:00', 'janderson'),
  ('ap-precalc', 'q1-2026', 15, '2026-09-25', 'Unit 5: Logarithmic Functions', 'Logarithmic Functions — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 16, '2026-09-28', 'Unit 6: Trigonometric Functions', 'Trigonometric Functions — lesson 1', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 17, '2026-09-30', 'Unit 6: Trigonometric Functions', 'Trigonometric Functions — lesson 2', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 18, '2026-10-02', 'Unit 6: Trigonometric Functions', 'Trigonometric Functions — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 19, '2026-10-05', 'Unit 7: Polar Functions', 'Polar Functions — lesson 1', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 20, '2026-10-07', 'Unit 7: Polar Functions', 'Polar Functions — lesson 2', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 21, '2026-10-09', 'Unit 7: Polar Functions', 'Polar Functions — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 22, '2026-10-12', 'Unit 8: Parametric Functions', 'Parametric Functions — lesson 1', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 23, '2026-10-14', 'Unit 8: Parametric Functions', 'Parametric Functions — lesson 2', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 24, '2026-10-16', 'Unit 8: Parametric Functions', 'Parametric Functions — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 25, '2026-10-19', 'Unit 9: Vectors and Matrices', 'Vectors and Matrices — lesson 1', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 26, '2026-10-21', 'Unit 9: Vectors and Matrices', 'Vectors and Matrices — lesson 2', false, NULL, NULL),
  ('ap-precalc', 'q1-2026', 27, '2026-10-23', 'Unit 9: Vectors and Matrices', 'Vectors and Matrices — lesson 3 (unit review)', false, NULL, NULL);

-- AP Calc AB: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-calc-ab', 'AP Calc AB', 'Senior', 'Dr John Anderson', 'blue', 52, 'in-progress', 'janderson');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-calc-ab', 'q1-2026', 1, '2026-08-24', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 1', true, '2026-08-24 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 2, '2026-08-26', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 2', true, '2026-08-26 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 3, '2026-08-28', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 3 (unit review)', true, '2026-08-28 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 4, '2026-08-31', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 1', true, '2026-08-31 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 5, '2026-09-02', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 2', true, '2026-09-02 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 6, '2026-09-04', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 3 (unit review)', true, '2026-09-04 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 7, '2026-09-07', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 1', true, '2026-09-07 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 8, '2026-09-09', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 2', true, '2026-09-09 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 9, '2026-09-11', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 3 (unit review)', true, '2026-09-11 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 10, '2026-09-14', 'Unit 4: Contextual Applications of Differentiation', 'Contextual Applications of Differentiation — lesson 1', true, '2026-09-14 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 11, '2026-09-16', 'Unit 4: Contextual Applications of Differentiation', 'Contextual Applications of Differentiation — lesson 2', true, '2026-09-16 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 12, '2026-09-18', 'Unit 4: Contextual Applications of Differentiation', 'Contextual Applications of Differentiation — lesson 3 (unit review)', true, '2026-09-18 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 13, '2026-09-21', 'Unit 5: Analytical Applications of Differentiation', 'Analytical Applications of Differentiation — lesson 1', true, '2026-09-21 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 14, '2026-09-23', 'Unit 5: Analytical Applications of Differentiation', 'Analytical Applications of Differentiation — lesson 2', true, '2026-09-23 16:00:00', 'janderson'),
  ('ap-calc-ab', 'q1-2026', 15, '2026-09-25', 'Unit 5: Analytical Applications of Differentiation', 'Analytical Applications of Differentiation — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 16, '2026-09-28', 'Unit 6: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 1', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 17, '2026-09-30', 'Unit 6: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 2', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 18, '2026-10-02', 'Unit 6: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 19, '2026-10-05', 'Unit 7: Differential Equations', 'Differential Equations — lesson 1', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 20, '2026-10-07', 'Unit 7: Differential Equations', 'Differential Equations — lesson 2', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 21, '2026-10-09', 'Unit 7: Differential Equations', 'Differential Equations — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 22, '2026-10-12', 'Unit 8: Applications of Integration', 'Applications of Integration — lesson 1', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 23, '2026-10-14', 'Unit 8: Applications of Integration', 'Applications of Integration — lesson 2', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 24, '2026-10-16', 'Unit 8: Applications of Integration', 'Applications of Integration — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 25, '2026-10-19', 'Unit 9: Exam Review', 'Exam Review — lesson 1', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 26, '2026-10-21', 'Unit 9: Exam Review', 'Exam Review — lesson 2', false, NULL, NULL),
  ('ap-calc-ab', 'q1-2026', 27, '2026-10-23', 'Unit 9: Exam Review', 'Exam Review — lesson 3 (unit review)', false, NULL, NULL);

-- AP Calc BC: 27 classes, 15 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-calc-bc', 'AP Calc BC', 'Senior', 'Dr John Anderson', 'blue', 56, 'in-progress', 'janderson');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-calc-bc', 'q1-2026', 1, '2026-08-24', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 1', true, '2026-08-24 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 2, '2026-08-25', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 2', true, '2026-08-25 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 3, '2026-08-26', 'Unit 1: Limits and Continuity', 'Limits and Continuity — lesson 3 (unit review)', true, '2026-08-26 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 4, '2026-08-31', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 1', true, '2026-08-31 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 5, '2026-09-01', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 2', true, '2026-09-01 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 6, '2026-09-02', 'Unit 2: Differentiation: Definition and Basic Rules', 'Differentiation: Definition and Basic Rules — lesson 3 (unit review)', true, '2026-09-02 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 7, '2026-09-07', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 1', true, '2026-09-07 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 8, '2026-09-08', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 2', true, '2026-09-08 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 9, '2026-09-09', 'Unit 3: Differentiation: Composite, Implicit, and Inverse Functions', 'Differentiation: Composite, Implicit, and Inverse Functions — lesson 3 (unit review)', true, '2026-09-09 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 10, '2026-09-14', 'Unit 4: Applications of Differentiation', 'Applications of Differentiation — lesson 1', true, '2026-09-14 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 11, '2026-09-15', 'Unit 4: Applications of Differentiation', 'Applications of Differentiation — lesson 2', true, '2026-09-15 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 12, '2026-09-16', 'Unit 4: Applications of Differentiation', 'Applications of Differentiation — lesson 3 (unit review)', true, '2026-09-16 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 13, '2026-09-21', 'Unit 5: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 1', true, '2026-09-21 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 14, '2026-09-22', 'Unit 5: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 2', true, '2026-09-22 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 15, '2026-09-23', 'Unit 5: Integration and Accumulation of Change', 'Integration and Accumulation of Change — lesson 3 (unit review)', true, '2026-09-23 16:00:00', 'janderson'),
  ('ap-calc-bc', 'q1-2026', 16, '2026-09-28', 'Unit 6: Differential Equations', 'Differential Equations — lesson 1', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 17, '2026-09-29', 'Unit 6: Differential Equations', 'Differential Equations — lesson 2', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 18, '2026-09-30', 'Unit 6: Differential Equations', 'Differential Equations — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 19, '2026-10-05', 'Unit 7: Applications of Integration', 'Applications of Integration — lesson 1', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 20, '2026-10-06', 'Unit 7: Applications of Integration', 'Applications of Integration — lesson 2', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 21, '2026-10-07', 'Unit 7: Applications of Integration', 'Applications of Integration — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 22, '2026-10-12', 'Unit 8: Parametric, Polar, and Vector Functions', 'Parametric, Polar, and Vector Functions — lesson 1', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 23, '2026-10-13', 'Unit 8: Parametric, Polar, and Vector Functions', 'Parametric, Polar, and Vector Functions — lesson 2', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 24, '2026-10-14', 'Unit 8: Parametric, Polar, and Vector Functions', 'Parametric, Polar, and Vector Functions — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 25, '2026-10-19', 'Unit 9: Infinite Sequences and Series', 'Infinite Sequences and Series — lesson 1', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 26, '2026-10-20', 'Unit 9: Infinite Sequences and Series', 'Infinite Sequences and Series — lesson 2', false, NULL, NULL),
  ('ap-calc-bc', 'q1-2026', 27, '2026-10-21', 'Unit 9: Infinite Sequences and Series', 'Infinite Sequences and Series — lesson 3 (unit review)', false, NULL, NULL);

-- AP Chemistry: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-chemistry', 'AP Chemistry', 'Junior', 'Dr Priya Patel', 'red', 52, 'in-progress', 'ppatel');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-chemistry', 'q1-2026', 1, '2026-08-24', 'Unit 1: Atomic Structure and Properties', 'Atomic Structure and Properties — lesson 1', true, '2026-08-24 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 2, '2026-08-26', 'Unit 1: Atomic Structure and Properties', 'Atomic Structure and Properties — lesson 2', true, '2026-08-26 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 3, '2026-08-28', 'Unit 1: Atomic Structure and Properties', 'Atomic Structure and Properties — lesson 3 (unit review)', true, '2026-08-28 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 4, '2026-08-31', 'Unit 2: Molecular and Ionic Bonding', 'Molecular and Ionic Bonding — lesson 1', true, '2026-08-31 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 5, '2026-09-02', 'Unit 2: Molecular and Ionic Bonding', 'Molecular and Ionic Bonding — lesson 2', true, '2026-09-02 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 6, '2026-09-04', 'Unit 2: Molecular and Ionic Bonding', 'Molecular and Ionic Bonding — lesson 3 (unit review)', true, '2026-09-04 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 7, '2026-09-07', 'Unit 3: Intermolecular Forces and Properties', 'Intermolecular Forces and Properties — lesson 1', true, '2026-09-07 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 8, '2026-09-09', 'Unit 3: Intermolecular Forces and Properties', 'Intermolecular Forces and Properties — lesson 2', true, '2026-09-09 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 9, '2026-09-11', 'Unit 3: Intermolecular Forces and Properties', 'Intermolecular Forces and Properties — lesson 3 (unit review)', true, '2026-09-11 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 10, '2026-09-14', 'Unit 4: Chemical Reactions', 'Chemical Reactions — lesson 1', true, '2026-09-14 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 11, '2026-09-16', 'Unit 4: Chemical Reactions', 'Chemical Reactions — lesson 2', true, '2026-09-16 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 12, '2026-09-18', 'Unit 4: Chemical Reactions', 'Chemical Reactions — lesson 3 (unit review)', true, '2026-09-18 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 13, '2026-09-21', 'Unit 5: Kinetics', 'Kinetics — lesson 1', true, '2026-09-21 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 14, '2026-09-23', 'Unit 5: Kinetics', 'Kinetics — lesson 2', true, '2026-09-23 16:00:00', 'ppatel'),
  ('ap-chemistry', 'q1-2026', 15, '2026-09-25', 'Unit 5: Kinetics', 'Kinetics — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 16, '2026-09-28', 'Unit 6: Thermodynamics', 'Thermodynamics — lesson 1', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 17, '2026-09-30', 'Unit 6: Thermodynamics', 'Thermodynamics — lesson 2', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 18, '2026-10-02', 'Unit 6: Thermodynamics', 'Thermodynamics — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 19, '2026-10-05', 'Unit 7: Equilibrium', 'Equilibrium — lesson 1', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 20, '2026-10-07', 'Unit 7: Equilibrium', 'Equilibrium — lesson 2', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 21, '2026-10-09', 'Unit 7: Equilibrium', 'Equilibrium — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 22, '2026-10-12', 'Unit 8: Acids and Bases', 'Acids and Bases — lesson 1', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 23, '2026-10-14', 'Unit 8: Acids and Bases', 'Acids and Bases — lesson 2', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 24, '2026-10-16', 'Unit 8: Acids and Bases', 'Acids and Bases — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 25, '2026-10-19', 'Unit 9: Applications of Thermodynamics', 'Applications of Thermodynamics — lesson 1', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 26, '2026-10-21', 'Unit 9: Applications of Thermodynamics', 'Applications of Thermodynamics — lesson 2', false, NULL, NULL),
  ('ap-chemistry', 'q1-2026', 27, '2026-10-23', 'Unit 9: Applications of Thermodynamics', 'Applications of Thermodynamics — lesson 3 (unit review)', false, NULL, NULL);

-- AP English Literature: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-english-lit', 'AP English Literature', 'Junior', 'Ms Sarah Wilson', 'green', 52, 'in-progress', 'swilson');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-english-lit', 'q1-2026', 1, '2026-08-24', 'Unit 1: Short Fiction I', 'Short Fiction I — lesson 1', true, '2026-08-24 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 2, '2026-08-26', 'Unit 1: Short Fiction I', 'Short Fiction I — lesson 2', true, '2026-08-26 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 3, '2026-08-28', 'Unit 1: Short Fiction I', 'Short Fiction I — lesson 3 (unit review)', true, '2026-08-28 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 4, '2026-08-31', 'Unit 2: Poetry I', 'Poetry I — lesson 1', true, '2026-08-31 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 5, '2026-09-02', 'Unit 2: Poetry I', 'Poetry I — lesson 2', true, '2026-09-02 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 6, '2026-09-04', 'Unit 2: Poetry I', 'Poetry I — lesson 3 (unit review)', true, '2026-09-04 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 7, '2026-09-07', 'Unit 3: Longer Fiction or Drama I', 'Longer Fiction or Drama I — lesson 1', true, '2026-09-07 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 8, '2026-09-09', 'Unit 3: Longer Fiction or Drama I', 'Longer Fiction or Drama I — lesson 2', true, '2026-09-09 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 9, '2026-09-11', 'Unit 3: Longer Fiction or Drama I', 'Longer Fiction or Drama I — lesson 3 (unit review)', true, '2026-09-11 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 10, '2026-09-14', 'Unit 4: Short Fiction II', 'Short Fiction II — lesson 1', true, '2026-09-14 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 11, '2026-09-16', 'Unit 4: Short Fiction II', 'Short Fiction II — lesson 2', true, '2026-09-16 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 12, '2026-09-18', 'Unit 4: Short Fiction II', 'Short Fiction II — lesson 3 (unit review)', true, '2026-09-18 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 13, '2026-09-21', 'Unit 5: Poetry II', 'Poetry II — lesson 1', true, '2026-09-21 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 14, '2026-09-23', 'Unit 5: Poetry II', 'Poetry II — lesson 2', true, '2026-09-23 16:00:00', 'swilson'),
  ('ap-english-lit', 'q1-2026', 15, '2026-09-25', 'Unit 5: Poetry II', 'Poetry II — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 16, '2026-09-28', 'Unit 6: Longer Fiction or Drama II', 'Longer Fiction or Drama II — lesson 1', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 17, '2026-09-30', 'Unit 6: Longer Fiction or Drama II', 'Longer Fiction or Drama II — lesson 2', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 18, '2026-10-02', 'Unit 6: Longer Fiction or Drama II', 'Longer Fiction or Drama II — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 19, '2026-10-05', 'Unit 7: Short Fiction III', 'Short Fiction III — lesson 1', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 20, '2026-10-07', 'Unit 7: Short Fiction III', 'Short Fiction III — lesson 2', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 21, '2026-10-09', 'Unit 7: Short Fiction III', 'Short Fiction III — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 22, '2026-10-12', 'Unit 8: Poetry III', 'Poetry III — lesson 1', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 23, '2026-10-14', 'Unit 8: Poetry III', 'Poetry III — lesson 2', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 24, '2026-10-16', 'Unit 8: Poetry III', 'Poetry III — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 25, '2026-10-19', 'Unit 9: Longer Fiction or Drama III', 'Longer Fiction or Drama III — lesson 1', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 26, '2026-10-21', 'Unit 9: Longer Fiction or Drama III', 'Longer Fiction or Drama III — lesson 2', false, NULL, NULL),
  ('ap-english-lit', 'q1-2026', 27, '2026-10-23', 'Unit 9: Longer Fiction or Drama III', 'Longer Fiction or Drama III — lesson 3 (unit review)', false, NULL, NULL);

-- AP Biology: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-biology', 'AP Biology', 'Sophomore', 'Mr Tom Teacher', 'teal', 52, 'in-progress', 'teacher1');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-biology', 'q1-2026', 1, '2026-08-24', 'Unit 1: Chemistry of Life', 'Chemistry of Life — lesson 1', true, '2026-08-24 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 2, '2026-08-26', 'Unit 1: Chemistry of Life', 'Chemistry of Life — lesson 2', true, '2026-08-26 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 3, '2026-08-28', 'Unit 1: Chemistry of Life', 'Chemistry of Life — lesson 3 (unit review)', true, '2026-08-28 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 4, '2026-08-31', 'Unit 2: Cell Structure and Function', 'Cell Structure and Function — lesson 1', true, '2026-08-31 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 5, '2026-09-02', 'Unit 2: Cell Structure and Function', 'Cell Structure and Function — lesson 2', true, '2026-09-02 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 6, '2026-09-04', 'Unit 2: Cell Structure and Function', 'Cell Structure and Function — lesson 3 (unit review)', true, '2026-09-04 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 7, '2026-09-07', 'Unit 3: Cellular Energetics', 'Cellular Energetics — lesson 1', true, '2026-09-07 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 8, '2026-09-09', 'Unit 3: Cellular Energetics', 'Cellular Energetics — lesson 2', true, '2026-09-09 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 9, '2026-09-11', 'Unit 3: Cellular Energetics', 'Cellular Energetics — lesson 3 (unit review)', true, '2026-09-11 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 10, '2026-09-14', 'Unit 4: Cell Communication and Cell Cycle', 'Cell Communication and Cell Cycle — lesson 1', true, '2026-09-14 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 11, '2026-09-16', 'Unit 4: Cell Communication and Cell Cycle', 'Cell Communication and Cell Cycle — lesson 2', true, '2026-09-16 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 12, '2026-09-18', 'Unit 4: Cell Communication and Cell Cycle', 'Cell Communication and Cell Cycle — lesson 3 (unit review)', true, '2026-09-18 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 13, '2026-09-21', 'Unit 5: Heredity', 'Heredity — lesson 1', true, '2026-09-21 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 14, '2026-09-23', 'Unit 5: Heredity', 'Heredity — lesson 2', true, '2026-09-23 16:00:00', 'teacher1'),
  ('ap-biology', 'q1-2026', 15, '2026-09-25', 'Unit 5: Heredity', 'Heredity — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 16, '2026-09-28', 'Unit 6: Gene Expression and Regulation', 'Gene Expression and Regulation — lesson 1', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 17, '2026-09-30', 'Unit 6: Gene Expression and Regulation', 'Gene Expression and Regulation — lesson 2', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 18, '2026-10-02', 'Unit 6: Gene Expression and Regulation', 'Gene Expression and Regulation — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 19, '2026-10-05', 'Unit 7: Natural Selection', 'Natural Selection — lesson 1', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 20, '2026-10-07', 'Unit 7: Natural Selection', 'Natural Selection — lesson 2', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 21, '2026-10-09', 'Unit 7: Natural Selection', 'Natural Selection — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 22, '2026-10-12', 'Unit 8: Ecology', 'Ecology — lesson 1', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 23, '2026-10-14', 'Unit 8: Ecology', 'Ecology — lesson 2', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 24, '2026-10-16', 'Unit 8: Ecology', 'Ecology — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 25, '2026-10-19', 'Unit 9: Biotechnology and Lab Review', 'Biotechnology and Lab Review — lesson 1', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 26, '2026-10-21', 'Unit 9: Biotechnology and Lab Review', 'Biotechnology and Lab Review — lesson 2', false, NULL, NULL),
  ('ap-biology', 'q1-2026', 27, '2026-10-23', 'Unit 9: Biotechnology and Lab Review', 'Biotechnology and Lab Review — lesson 3 (unit review)', false, NULL, NULL);

-- AP Computer Science: 27 classes, 14 complete
INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)
VALUES ('ap-cs', 'AP Computer Science', 'Senior', 'Mr David Lee', 'purple', 52, 'in-progress', 'dlee');
INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic, completed, completed_at, completed_by) VALUES
  ('ap-cs', 'q1-2026', 1, '2026-08-25', 'Unit 1: Primitive Types', 'Primitive Types — lesson 1', true, '2026-08-25 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 2, '2026-08-26', 'Unit 1: Primitive Types', 'Primitive Types — lesson 2', true, '2026-08-26 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 3, '2026-08-27', 'Unit 1: Primitive Types', 'Primitive Types — lesson 3 (unit review)', true, '2026-08-27 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 4, '2026-09-01', 'Unit 2: Using Objects', 'Using Objects — lesson 1', true, '2026-09-01 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 5, '2026-09-02', 'Unit 2: Using Objects', 'Using Objects — lesson 2', true, '2026-09-02 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 6, '2026-09-03', 'Unit 2: Using Objects', 'Using Objects — lesson 3 (unit review)', true, '2026-09-03 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 7, '2026-09-08', 'Unit 3: Boolean Expressions and if Statements', 'Boolean Expressions and if Statements — lesson 1', true, '2026-09-08 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 8, '2026-09-09', 'Unit 3: Boolean Expressions and if Statements', 'Boolean Expressions and if Statements — lesson 2', true, '2026-09-09 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 9, '2026-09-10', 'Unit 3: Boolean Expressions and if Statements', 'Boolean Expressions and if Statements — lesson 3 (unit review)', true, '2026-09-10 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 10, '2026-09-15', 'Unit 4: Iteration', 'Iteration — lesson 1', true, '2026-09-15 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 11, '2026-09-16', 'Unit 4: Iteration', 'Iteration — lesson 2', true, '2026-09-16 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 12, '2026-09-17', 'Unit 4: Iteration', 'Iteration — lesson 3 (unit review)', true, '2026-09-17 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 13, '2026-09-22', 'Unit 5: Writing Classes', 'Writing Classes — lesson 1', true, '2026-09-22 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 14, '2026-09-23', 'Unit 5: Writing Classes', 'Writing Classes — lesson 2', true, '2026-09-23 16:00:00', 'dlee'),
  ('ap-cs', 'q1-2026', 15, '2026-09-24', 'Unit 5: Writing Classes', 'Writing Classes — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 16, '2026-09-29', 'Unit 6: Array', 'Array — lesson 1', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 17, '2026-09-30', 'Unit 6: Array', 'Array — lesson 2', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 18, '2026-10-01', 'Unit 6: Array', 'Array — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 19, '2026-10-06', 'Unit 7: ArrayList', 'ArrayList — lesson 1', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 20, '2026-10-07', 'Unit 7: ArrayList', 'ArrayList — lesson 2', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 21, '2026-10-08', 'Unit 7: ArrayList', 'ArrayList — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 22, '2026-10-13', 'Unit 8: 2D Array', '2D Array — lesson 1', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 23, '2026-10-14', 'Unit 8: 2D Array', '2D Array — lesson 2', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 24, '2026-10-15', 'Unit 8: 2D Array', '2D Array — lesson 3 (unit review)', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 25, '2026-10-20', 'Unit 9: Inheritance', 'Inheritance — lesson 1', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 26, '2026-10-21', 'Unit 9: Inheritance', 'Inheritance — lesson 2', false, NULL, NULL),
  ('ap-cs', 'q1-2026', 27, '2026-10-22', 'Unit 9: Inheritance', 'Inheritance — lesson 3 (unit review)', false, NULL, NULL);

INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-14', 90);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-15', 60);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-16', 75);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-17', 45);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-18', 30);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-21', 120);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-22', 80);
INSERT INTO study_session (username, day, minutes) VALUES ('student1', '2026-09-23', 55);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-14', 45);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-16', 60);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-17', 90);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-18', 40);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-21', 70);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-22', 50);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-24', 100);
INSERT INTO study_session (username, day, minutes) VALUES ('slewis', '2026-09-25', 35);
