#!/usr/bin/env python3
"""Regenerates src/main/resources/db/dev/V2__seed.sql (dev-only seed data for learning-service).

    python3 tools/gen_seed.py > src/main/resources/db/dev/V2__seed.sql

Edit COURSES / STUDY below to change the seed, then regenerate. Flyway runs the file once and
records it, so plain INSERTs are fine. Only the dev profile loads db/dev; prod never sees it.
If you change an already-applied seed, wipe the volume first: docker compose down -v
"""
from datetime import date, datetime, timedelta

TERM_ID = "q1-2026"
TERM_NAME = "Q1 \u00b7 Fall 2026"
TERM_START = date(2026, 8, 24)
TERM_END = date(2026, 10, 23)
# Classes on or before this date are already marked complete in the seed.
DONE_THROUGH = date(2026, 9, 23)

MWF, MTUW, TUWTH = (0, 2, 4), (0, 1, 2), (1, 2, 3)  # Python weekday(): Mon=0

# id, name, grade, teacher name, teacher username, color, class days, nine unit titles (3 lessons each)
COURSES = [
    ("ap-precalc", "AP Pre Calculus", "Junior", "Dr John Anderson", "janderson", "blue", MWF,
     ["Functions and Graphs", "Polynomial Functions", "Rational Functions", "Exponential Functions",
      "Logarithmic Functions", "Trigonometric Functions", "Polar Functions", "Parametric Functions",
      "Vectors and Matrices"]),
    ("ap-calc-ab", "AP Calc AB", "Senior", "Dr John Anderson", "janderson", "blue", MWF,
     ["Limits and Continuity", "Differentiation: Definition and Basic Rules",
      "Differentiation: Composite, Implicit, and Inverse Functions",
      "Contextual Applications of Differentiation", "Analytical Applications of Differentiation",
      "Integration and Accumulation of Change", "Differential Equations",
      "Applications of Integration", "Exam Review"]),
    ("ap-calc-bc", "AP Calc BC", "Senior", "Dr John Anderson", "janderson", "blue", MTUW,
     ["Limits and Continuity", "Differentiation: Definition and Basic Rules",
      "Differentiation: Composite, Implicit, and Inverse Functions", "Applications of Differentiation",
      "Integration and Accumulation of Change", "Differential Equations",
      "Applications of Integration", "Parametric, Polar, and Vector Functions",
      "Infinite Sequences and Series"]),
    ("ap-chemistry", "AP Chemistry", "Junior", "Dr Priya Patel", "ppatel", "red", MWF,
     ["Atomic Structure and Properties", "Molecular and Ionic Bonding",
      "Intermolecular Forces and Properties", "Chemical Reactions", "Kinetics", "Thermodynamics",
      "Equilibrium", "Acids and Bases", "Applications of Thermodynamics"]),
    ("ap-english-lit", "AP English Literature", "Junior", "Ms Sarah Wilson", "swilson", "green", MWF,
     ["Short Fiction I", "Poetry I", "Longer Fiction or Drama I", "Short Fiction II", "Poetry II",
      "Longer Fiction or Drama II", "Short Fiction III", "Poetry III", "Longer Fiction or Drama III"]),
    ("ap-biology", "AP Biology", "Sophomore", "Mr Tom Teacher", "teacher1", "teal", MWF,
     ["Chemistry of Life", "Cell Structure and Function", "Cellular Energetics",
      "Cell Communication and Cell Cycle", "Heredity", "Gene Expression and Regulation",
      "Natural Selection", "Ecology", "Biotechnology and Lab Review"]),
    ("ap-cs", "AP Computer Science", "Senior", "Mr David Lee", "dlee", "purple", TUWTH,
     ["Primitive Types", "Using Objects", "Boolean Expressions and if Statements", "Iteration",
      "Writing Classes", "Array", "ArrayList", "2D Array", "Inheritance"]),
]

# username -> (day, minutes)
STUDY = {
    "student1": [("2026-09-14", 90), ("2026-09-15", 60), ("2026-09-16", 75), ("2026-09-17", 45),
                 ("2026-09-18", 30), ("2026-09-21", 120), ("2026-09-22", 80), ("2026-09-23", 55)],
    "slewis": [("2026-09-14", 45), ("2026-09-16", 60), ("2026-09-17", 90), ("2026-09-18", 40),
               ("2026-09-21", 70), ("2026-09-22", 50), ("2026-09-24", 100), ("2026-09-25", 35)],
}


def q(s):
    return "'" + s.replace("'", "''") + "'"


def class_dates(days):
    d, out = TERM_START, []
    while d <= TERM_END:
        if d.weekday() in days:
            out.append(d)
        d += timedelta(days=1)
    return out


def main():
    print("-- Dev-only seed data for learning-service (Flyway V2, loaded only by the dev profile).")
    print("-- GENERATED by tools/gen_seed.py - edit that script and regenerate, do not hand-edit.")
    print()
    print("INSERT INTO term (id, name, start_date, end_date, is_current, max_credits, quarter, academic_year)")
    print(f"VALUES ({q(TERM_ID)}, {q(TERM_NAME)}, '{TERM_START}', '{TERM_END}', true, 30, 1, '2026-2027');")
    print()
    for cid, name, grade, teacher, tuser, color, days, units in COURSES:
        dates = class_dates(days)
        assert len(dates) == 27 == len(units) * 3, (cid, len(dates))
        done = sum(1 for d in dates if d <= DONE_THROUGH)
        pct = round(done * 100 / len(dates))
        status = "completed" if done == len(dates) else ("in-progress" if done else "not-started")
        print(f"-- {name}: {len(dates)} classes, {done} complete")
        print("INSERT INTO course (id, name, grade_level, teacher, color, percent, status, teacher_username)")
        print(f"VALUES ({q(cid)}, {q(name)}, {q(grade)}, {q(teacher)}, {q(color)}, {pct}, {q(status)}, {q(tuser)});")
        rows = []
        for i, d in enumerate(dates):
            unit, lesson = i // 3 + 1, i % 3 + 1
            unit_name = units[unit - 1]
            title = f"Unit {unit}: {unit_name}"
            topic = f"{unit_name} \u2014 lesson {lesson}" + (" (unit review)" if lesson == 3 else "")
            if d <= DONE_THROUGH:
                stamp = datetime(d.year, d.month, d.day, 16, 0).strftime("%Y-%m-%d %H:%M:%S")
                comp = f"true, '{stamp}', {q(tuser)}"
            else:
                comp = "false, NULL, NULL"
            rows.append(f"  ({q(cid)}, {q(TERM_ID)}, {i + 1}, '{d}', {q(title)}, {q(topic)}, {comp})")
        print("INSERT INTO lesson_plan_item (course_id, term_id, class_number, class_date, title, topic,"
              " completed, completed_at, completed_by) VALUES")
        print(",\n".join(rows) + ";")
        print()
    for user, rows in STUDY.items():
        for day, minutes in rows:
            print(f"INSERT INTO study_session (username, day, minutes) VALUES ({q(user)}, '{day}', {minutes});")


if __name__ == "__main__":
    main()
